name: Deploy .NET to Elastic Beanstalk

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' 

      - name: Publish .NET App
        run: dotnet publish -c Release -o publish

      - name: Zip Publish Folder
        run: |
          cd publish
          zip -r ../app.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: My.NetGymproj
          environment_name: MyNetGymproj-env
          version_label: v-${{ github.run_number }}
          region: 	ap-south-1
          deployment_package: app.zip
